apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: 'Publish evidence item'
description: 'Capture information, including commit ID and message, as evidence of work done by the workflow run.'

inputs:
  content:
    description: 'Information to capture as an evidence item for the workflow run.'
    required: true
  format:
    description: 'Used to render the evidence item.'
    default: MARKDOWN

runs:
  using: composite
  steps:
    - id: captureCommitInfo
      name: 'Capture Commit Information'
      run: |
        # Get the commit ID and message
        COMMIT_ID=$(git rev-parse HEAD)
        COMMIT_MSG=$(git log -1 --pretty=%B)

        # Combine commit information with provided content
        FULL_CONTENT="${{ inputs.content }}\n\nCommit ID: $COMMIT_ID\nCommit Message: $COMMIT_MSG"
        
        # Export content to be used in the next step
        echo "FULL_CONTENT=$FULL_CONTENT" >> /tekton/results/content

    - id: postWorkflowEvidenceItem
      name: 'Post Workflow Evidence Item'
      image: alpine/curl:latest
      script: |
        # Prepare content for the API call
        PREPARED_CONTENT=$(echo "$FULL_CONTENT" | sed 's/"/\\"/g' | sed 's/$/\\n/g' | tr -d '\n')

        # Make the API call to post evidence
        response=$(curl --fail-with-body -X 'POST' "$URL/v1/workflows/artifact" \
            -H "Authorization: Bearer $JWT" \
            -H 'Content-Type: application/json' \
            --data-binary '{"stepId": "'"$STEP_ID"'", "evidence": {"value": "'"$PREPARED_CONTENT"'", "format": "'"$FORMAT"'"}}') || command_failed=1

        if [ ${command_failed:-0} -eq 1 ]; then
          echo "API call failed: '$response'"
          exit 1
        fi
      env:
        STEP_ID: ${{ step.id }}
        JWT: ${{ cloudbees.api.token }}
        URL: ${{ cloudbees.api.url }}
        FULL_CONTENT: ${{ results.content }}
        FORMAT: ${{ inputs.format }}
